version: '3.4'
services:
    ftx-safeboard:
        image: node:16.3.0-alpine3.13
        container_name: ftx-safeboard-dev
        volumes: 
            - ./webapp:/app
        # env_file: ./webapp/.env
        environment: 
            - NODE_ENV:development
        command: /bin/sh -c "cd /app && yarn start"
    proxy:
        image: nginx:alpine
        ports:
            - 3000:80
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    cors:
        image: ftx-safeboard-cors
        build:
            context: ./backend
            dockerfile: "./Dockerfile"
        container_name: ftx-safeboard-cors
        ports:
            - 3004:8080