GET http://localhost:3000/api/testonly/testjwt
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpMdU5wQlc2Ti1RU3M3UUJycHJudiJ9.eyJpc3MiOiJodHRwczovL2Rldi0ta2V5NnV2Yi51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDg2MTczMjIxNzAzMTgwOTU1MDIiLCJhdWQiOlsiaHR0cHM6Ly9kZXYtLWtleTZ1dmIudXMuYXV0aDAuY29tL2FwaS92Mi8iLCJodHRwczovL2Rldi0ta2V5NnV2Yi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjMwMTQ2MTQ3LCJleHAiOjE2MzAyMzI1NDcsImF6cCI6IlhYT3JXYlJ3NU5wVmZPaGl0Y09qNVJKamtOWlJoZ082Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCByZWFkOmN1cnJlbnRfdXNlciB1cGRhdGU6Y3VycmVudF91c2VyX21ldGFkYXRhIn0.FtUM7zASECvdi6iaVXMBRsMncqoNK-unV7wZXuX4iWbY8FTAWONUjmTJLswtAhV0iBLbou48Ycj2CwjzQ92gOiisewVWdP7jKbJL6b2B2uiPagPICYxZhFz2nSkE4E7Cysy9DTixjKLYczFbHrSX-JgbgURsIF5mgbg8FrMSVwMVUpv02JOMIhx9dKbQ2Dv9CLFiySO3iCH8Ubi88mJvpFzeo2ih57GgiNg6GC5eVjvsSGAWXTutaTnsfDW2sGnPGXGqo3HVkqb5Zd85233eqRg7KI4gloT2LDrKXUp8I60O5_tIIVrFPwPmDksasZR8JfsS33XqyVPRe3PMwRknWA